title: Github Pages Learning Lab
author: mneca15
email: neca_205@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
  This page is the result of a step-by-step guide from the Github Learning Lab.

# social links
github_username:  https://github.com/mneca15

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
